//
// Created by admin on 2024/8/2.
//

#ifndef WHALE_PLATFORM_WINDOWS_RESOURCES_HEADER
#define WHALE_PLATFORM_WINDOWS_RESOURCES_HEADER

#define IDI_APP_ICON    100
#define IDI_APP_ICON_SM 101

#endif
